version: '3'
services:
  frontend:
    image: node:12
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: yarn serve
    working_dir: /app
    depends_on:
      - build

  build:
    image: node:12
    command: yarn install
    volumes:
      - .:/app
    working_dir: /app
