FROM php:7.4
# COPY apache2.conf /etc/apache2
# RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
  && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
  && docker-php-ext-install pdo_mysql \
